{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "en-GB",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/sgbsql01 database windows net;KPI_Dashboards",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "sgbsql01.database.windows.net",
            "database": "KPI_Dashboards"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "sgbsql01.database.windows.net;KPI_Dashboards",
          "Username": "sgbsql01_admin",
          "EncryptConnection": true
        }
      }
    ],
    "tables": [
      {
        "name": "vw CSI New Sales",
        "columns": [
          {
            "name": "SalesID",
            "dataType": "int64",
            "sourceColumn": "SalesID"
          },
          {
            "name": "DS_PK",
            "dataType": "int64",
            "sourceColumn": "DS_PK"
          },
          {
            "name": "DS_SK",
            "dataType": "int64",
            "sourceColumn": "DS_SK"
          },
          {
            "name": "Contact person",
            "dataType": "string",
            "sourceColumn": "Contact person"
          },
          {
            "name": "Company",
            "dataType": "string",
            "sourceColumn": "Company"
          },
          {
            "name": "Company ID",
            "dataType": "string",
            "sourceColumn": "Company ID"
          },
          {
            "name": "Interaction Date",
            "dataType": "dateTime",
            "sourceColumn": "Interaction Date",
            "formatString": "dd/MM/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Interview Date",
            "dataType": "dateTime",
            "sourceColumn": "Interview Date",
            "formatString": "dd/MM/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Main Dealer",
            "dataType": "string",
            "sourceColumn": "Main Dealer"
          },
          {
            "name": "Dealer",
            "dataType": "string",
            "sourceColumn": "Dealer"
          },
          {
            "name": "Salesperson",
            "dataType": "string",
            "sourceColumn": "Salesperson"
          },
          {
            "name": "New Contact Y/N",
            "dataType": "string",
            "sourceColumn": "New Contact Y/N"
          },
          {
            "name": "New Contact",
            "dataType": "string",
            "sourceColumn": "New Contact"
          },
          {
            "name": "New Phone Y/N",
            "dataType": "string",
            "sourceColumn": "New Phone Y/N"
          },
          {
            "name": "New Phone",
            "dataType": "string",
            "sourceColumn": "New Phone"
          },
          {
            "name": "Contact Via Email Y/N",
            "dataType": "string",
            "sourceColumn": "Contact Via Email Y/N"
          },
          {
            "name": "New Email Y/N",
            "dataType": "string",
            "sourceColumn": "New Email Y/N"
          },
          {
            "name": "New Email",
            "dataType": "string",
            "sourceColumn": "New Email"
          },
          {
            "name": "Remove Contact Y/N",
            "dataType": "string",
            "sourceColumn": "Remove Contact Y/N"
          },
          {
            "name": "Name Withheld Yes/No",
            "dataType": "string",
            "sourceColumn": "Name Withheld Yes/No"
          },
          {
            "name": "Phone Answered Y/N",
            "dataType": "string",
            "sourceColumn": "Phone Answered Y/N"
          },
          {
            "name": "Survey Completed Y/N",
            "dataType": "string",
            "sourceColumn": "Survey Completed Y/N"
          },
          {
            "name": "Further Comments",
            "dataType": "string",
            "sourceColumn": "Further Comments"
          },
          {
            "name": "Question ID",
            "dataType": "string",
            "sourceColumn": "Question ID"
          },
          {
            "name": "Question",
            "dataType": "string",
            "sourceColumn": "Question",
            "sortByColumn": "Question ID"
          },
          {
            "name": "Comments",
            "dataType": "string",
            "sourceColumn": "Comments"
          },
          {
            "name": "Points",
            "dataType": "string",
            "sourceColumn": "Points"
          },
          {
            "name": "Index",
            "dataType": "int64",
            "sourceColumn": "Index"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "MonthNo",
            "dataType": "int64",
            "sourceColumn": "MonthNo"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Points TXT",
            "dataType": "string",
            "sourceColumn": "Points TXT"
          },
          {
            "name": "Points TxT filter",
            "dataType": "string",
            "sourceColumn": "Points TxT filter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Quarter Sort",
            "dataType": "string",
            "sourceColumn": "Quarter Sort"
          },
          {
            "name": "Region ID",
            "dataType": "string",
            "sourceColumn": "Region ID"
          },
          {
            "name": "Contact Changed",
            "dataType": "string",
            "sourceColumn": "Contact Changed"
          },
          {
            "type": "calculated",
            "name": "NewSales MTD",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI New Sales'[Interaction Date])",
              "RETURN",
              "IF(MONTH('vw CSI New Sales'[Interaction Date])=MONTH(MAXDATE)&&YEAR('vw CSI New Sales'[Interaction Date])=YEAR(MAXDATE),TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "NewSales PM",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI New Sales'[Interaction Date])",
              "RETURN",
              "IF(MONTH('vw CSI New Sales'[Interaction Date])=MONTH(MAXDATE)-1&&YEAR('vw CSI New Sales'[Interaction Date])=YEAR(MAXDATE),TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "NewSales YTD",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI New Sales'[Interaction Date])",
              "RETURN",
              "IF(YEAR('vw CSI New Sales'[Interaction Date])=YEAR(MAXDATE),TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "NewSales LY",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI New Sales'[Interaction Date])",
              "RETURN",
              "IF(YEAR('vw CSI New Sales'[Interaction Date])=YEAR(MAXDATE)-1,TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "NewSales Rollin 12 Months",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI New Sales'[Interaction Date])",
              "RETURN",
              "IF('vw CSI New Sales'[Interaction Date]>=DATE(YEAR(MAXDATE)-1,MONTH(MAXDATE),DAY(MAXDATE))&&'vw CSI New Sales'[Interaction Date]<=MAXDATE,TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Question Filter",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "IF(OR('vw CSI New Sales'[Question]=\"Overall performance\",'vw CSI New Sales'[Question]=\"Recommendation\"),FALSE(),IF('vw CSI New Sales'[Question]=\"Repurchase\",FALSE(),TRUE()))",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Interval",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MaxDate =",
              "    MAX ( 'vw CSI New Sales'[Interaction Date] )",
              "RETURN",
              "    IF (",
              "        DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 0,",
              "        11,",
              "        IF (",
              "            DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 1,",
              "            10,",
              "            IF (",
              "                DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 2,",
              "                9,",
              "                IF (",
              "                    DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 3,",
              "                    8,",
              "                    IF (",
              "                        DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 4,",
              "                        7,",
              "                        IF (",
              "                            DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 5,",
              "                            6,",
              "                            IF (",
              "                                DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 6,",
              "                                5,",
              "                                IF (",
              "                                    DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 7,",
              "                                    4,",
              "                                    IF (",
              "                                        DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 8,",
              "                                        3,",
              "                                        IF (",
              "                                            DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 9,",
              "                                            2,",
              "                                            IF (",
              "                                                DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 10,",
              "                                                1,",
              "                                                IF (",
              "                                                    DATEDIFF ( 'vw CSI New Sales'[Interaction Date], MaxDate, MONTH ) = 11,",
              "                                                    0,",
              "                                                    100",
              "                                                )",
              "                                            )",
              "                                        )",
              "                                    )",
              "                                )",
              "                            )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )"
            ]
          },
          {
            "name": "Month Year",
            "dataType": "string",
            "sourceColumn": "Month Year",
            "sortByColumn": "Interval"
          },
          {
            "name": "Rolling Month Sort",
            "dataType": "int64",
            "sourceColumn": "Rolling Month Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    #\"dbo_vw CSI New Sales\" = Source{[Schema=\"dbo\",Item=\"vw CSI New Sales\"]}[Data]",
                "in",
                "    #\"dbo_vw CSI New Sales\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Selected New Sales Period",
            "expression": "SELECTEDVALUE('CSI Time Intelligence'[Period])"
          },
          {
            "name": "Selected Main Dealer NewSales",
            "expression": "IF(ISFILTERED('vw CSI New Sales'[Main dealer]),SELECTEDVALUE('vw CSI New Sales'[Main dealer]),\"All Dealers\")"
          },
          {
            "name": "Selected  Dealer NewSales",
            "expression": "IF(ISFILTERED('vw CSI New Sales'[Dealer]),SELECTEDVALUE('vw CSI New Sales'[Dealer]),\"All Dealers\")"
          },
          {
            "name": "Reporting Period NewSales",
            "expression": "IF(ISFILTERED('CSI Time Intelligence'[Period]),SELECTEDVALUE('CSI Time Intelligence'[Period]),\"All Periods\")"
          },
          {
            "name": "NewSales",
            "expression": "\"New Sales\""
          },
          {
            "name": "New Sales Tot Questions",
            "expression": "0+CALCULATE(DISTINCTCOUNT('vw CSI New Sales'[SalesID]))",
            "formatString": "#,0"
          },
          {
            "name": "New Sales Sample Size",
            "expression": [
              "",
              "IF (",
              "    [Selected New Sales Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [New Sales Tot Questions],",
              "        'vw CSI New Sales'[NewSales YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected New Sales Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [New Sales Tot Questions],",
              "           'vw CSI New Sales'[NewSales PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected New Sales Period] = \"Month To Date\",",
              "            CALCULATE (",
              "               [New Sales Tot Questions],",
              "               'vw CSI New Sales'[NewSales MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected New Sales Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [New Sales Tot Questions],",
              "                  'vw CSI New Sales'[NewSales Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected New Sales Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [New Sales Tot Questions],",
              "                      'vw CSI New Sales'[NewSales LY] = TRUE ()",
              "                    ),",
              "                    [New Sales Tot Questions]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Completed New Sales Survey",
            "expression": "CALCULATE([New Sales Sample Size],'vw CSI New Sales'[Survey Completed Y/N]=\"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Call Answered",
            "expression": "CALCULATE([New Sales Sample Size],'vw CSI New Sales'[Phone Answered Y/N]=\"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Contact After first Delivery %",
            "expression": "0+DIVIDE(CALCULATE('vw CSI New Sales'[New Sales Sample Size],'vw CSI New Sales'[Question]=\"Contacted after delivery (Yes/No)\",'vw CSI New Sales'[Points]=\"Yes\"),'vw CSI New Sales'[New Sales Sample Size])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "New Sales Index",
            "expression": "0+CALCULATE(AVERAGE('vw CSI New Sales'[Index]),'vw CSI New Sales'[Points TxT filter]=\"TRUE\")",
            "formatString": "0.0"
          },
          {
            "name": "CSI New Sales Index",
            "expression": [
              "",
              "IF (",
              "    [Selected New Sales Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [New Sales Index],",
              "        'vw CSI New Sales'[NewSales YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected New Sales Period]= \"Previous Month\",",
              "        CALCULATE (",
              "         [New Sales Index],",
              "           'vw CSI New Sales'[NewSales PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected New Sales Period] = \"Month To Date\",",
              "            CALCULATE (",
              "               [New Sales Index],",
              "               'vw CSI New Sales'[NewSales MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected New Sales Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                     [New Sales Index],",
              "                  'vw CSI New Sales'[NewSales Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected New Sales Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                        [New Sales Index],",
              "                      'vw CSI New Sales'[NewSales LY] = TRUE ()",
              "                    ),",
              "                      [New Sales Index]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "CSI New Sales Index (Card)",
            "expression": [
              "",
              "IF (",
              "    [Selected New Sales Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [New Sales Index],",
              "        'vw CSI New Sales'[NewSales YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected New Sales Period]= \"Previous Month\",",
              "        CALCULATE (",
              "         [New Sales Index],",
              "           'vw CSI New Sales'[NewSales PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected New Sales Period] = \"Month To Date\",",
              "            CALCULATE (",
              "               [New Sales Index],",
              "               'vw CSI New Sales'[NewSales MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected New Sales Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                     [New Sales Index],",
              "                  'vw CSI New Sales'[NewSales Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected New Sales Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                        [New Sales Index],",
              "                      'vw CSI New Sales'[NewSales LY] = TRUE ()",
              "                    ),",
              "                      [New Sales Index]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Completed New Sales Survey Graph",
            "expression": "CALCULATE([New Sales Sample Size],'vw CSI New Sales'[Survey Completed Y/N]=\"Y\",'vw CSI New Sales'[Points TxT filter]=\"TRUE\")",
            "formatString": "#,0"
          },
          {
            "name": "New Sales Index 2",
            "expression": "0+CALCULATE(AVERAGE('vw CSI New Sales'[Index]),'vw CSI New Sales'[Points TxT filter]=\"TRUE\",'vw CSI New Sales'[Question Filter]=TRUE())",
            "formatString": "0.0"
          },
          {
            "name": "CSI New Sales Index (Card 2)",
            "expression": [
              "",
              "IF (",
              "    [Selected New Sales Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [New Sales Index 2],",
              "        'vw CSI New Sales'[NewSales YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected New Sales Period]= \"Previous Month\",",
              "        CALCULATE (",
              "         [New Sales Index 2],",
              "           'vw CSI New Sales'[NewSales PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected New Sales Period] = \"Month To Date\",",
              "            CALCULATE (",
              "               [New Sales Index 2],",
              "               'vw CSI New Sales'[NewSales MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected New Sales Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                     [New Sales Index 2],",
              "                  'vw CSI New Sales'[NewSales Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected New Sales Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                        [New Sales Index 2],",
              "                      'vw CSI New Sales'[NewSales LY] = TRUE ()",
              "                    ),",
              "                      [New Sales Index 2]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Sales YTD",
            "expression": "CALCULATE([CSI New Sales Index 2(Table)],'vw CSI New Sales'[NewSales YTD]=TRUE())",
            "formatString": "0.0"
          },
          {
            "name": "New Sales Index 2(Table)",
            "expression": "CALCULATE(AVERAGE('vw CSI New Sales'[Index]),'vw CSI New Sales'[Points TxT filter]=\"TRUE\",'vw CSI New Sales'[Question Filter]=TRUE())",
            "formatString": "0.0"
          },
          {
            "name": "CSI New Sales Index 2(Table)",
            "expression": [
              "",
              "IF (",
              "    [Selected New Sales Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [New Sales Index 2(Table)],",
              "        'vw CSI New Sales'[NewSales YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected New Sales Period]= \"Previous Month\",",
              "        CALCULATE (",
              "         [New Sales Index 2(Table)],",
              "           'vw CSI New Sales'[NewSales PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected New Sales Period] = \"Month To Date\",",
              "            CALCULATE (",
              "               [New Sales Index 2(Table)],",
              "               'vw CSI New Sales'[NewSales MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected New Sales Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                     [New Sales Index 2(Table)],",
              "                  'vw CSI New Sales'[NewSales Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected New Sales Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                        [New Sales Index 2(Table)],",
              "                      'vw CSI New Sales'[NewSales LY] = TRUE ()",
              "                    ),",
              "                      [New Sales Index 2(Table)]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "New Sales Tot Questions (Table)",
            "expression": "CALCULATE(DISTINCTCOUNT('vw CSI New Sales'[SalesID]))",
            "formatString": "#,0"
          },
          {
            "name": "New Sales Sample Size(Table)",
            "expression": [
              "",
              "IF (",
              "    [Selected New Sales Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [New Sales Tot Questions (Table)],",
              "        'vw CSI New Sales'[NewSales YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected New Sales Period]= \"Previous Month\",",
              "        CALCULATE (",
              "            [New Sales Tot Questions (Table)],",
              "           'vw CSI New Sales'[NewSales PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected New Sales Period] = \"Month To Date\",",
              "            CALCULATE (",
              "                [New Sales Tot Questions (Table)],",
              "               'vw CSI New Sales'[NewSales MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected New Sales Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [New Sales Tot Questions (Table)],",
              "                  'vw CSI New Sales'[NewSales Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected New Sales Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [New Sales Tot Questions (Table)],",
              "                      'vw CSI New Sales'[NewSales LY] = TRUE ()",
              "                    ),",
              "                    [New Sales Tot Questions (Table)]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "New Sales Index (Table)",
            "expression": "CALCULATE(AVERAGE('vw CSI New Sales'[Index]),'vw CSI New Sales'[Index]<>0)",
            "formatString": "0.0"
          },
          {
            "name": "CSI New Sales Index (Table)",
            "expression": [
              "",
              "IF (",
              "    [Selected New Sales Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [New Sales Index (Table)],",
              "        'vw CSI New Sales'[NewSales YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected New Sales Period]= \"Previous Month\",",
              "        CALCULATE (",
              "      [New Sales Index (Table)],",
              "           'vw CSI New Sales'[NewSales PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected New Sales Period] = \"Month To Date\",",
              "            CALCULATE (",
              "                [New Sales Index (Table)],",
              "               'vw CSI New Sales'[NewSales MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected New Sales Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                            [New Sales Index (Table)],",
              "                  'vw CSI New Sales'[NewSales Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected New Sales Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                        [New Sales Index (Table)],",
              "                      'vw CSI New Sales'[NewSales LY] = TRUE ()",
              "                    ),",
              "                    [New Sales Index (Table)]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          }
        ]
      },
      {
        "name": "dim Date",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Year Name",
            "dataType": "string",
            "sourceColumn": "Year Name"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Quarter Name",
            "dataType": "string",
            "sourceColumn": "Quarter Name"
          },
          {
            "name": "Quarter Year Name",
            "dataType": "string",
            "sourceColumn": "Quarter Year Name"
          },
          {
            "name": "Week Start Date",
            "dataType": "dateTime",
            "sourceColumn": "Week Start Date"
          },
          {
            "name": "Week Name",
            "dataType": "string",
            "sourceColumn": "Week Name"
          },
          {
            "name": "Day Name",
            "dataType": "string",
            "sourceColumn": "Day Name"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day"
          },
          {
            "name": "Short Day Name",
            "dataType": "string",
            "sourceColumn": "Short Day Name"
          },
          {
            "name": "Short Month Name",
            "dataType": "string",
            "sourceColumn": "Short Month Name"
          },
          {
            "name": "Day Of Week",
            "dataType": "int64",
            "sourceColumn": "Day Of Week"
          },
          {
            "name": "Year Month",
            "dataType": "int64",
            "sourceColumn": "Year Month"
          },
          {
            "name": "Is Scottish Public Holiday",
            "dataType": "boolean",
            "sourceColumn": "Is Scottish Public Holiday"
          },
          {
            "name": "Is English Public Holiday",
            "dataType": "boolean",
            "sourceColumn": "Is English Public Holiday"
          },
          {
            "name": "Is Current Revenue Period",
            "dataType": "boolean",
            "sourceColumn": "Is Current Revenue Period"
          },
          {
            "name": "Is Previous Revenue Period",
            "dataType": "boolean",
            "sourceColumn": "Is Previous Revenue Period"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    dim_Date = Source{[Schema=\"dim\",Item=\"Date\"]}[Data]",
                "in",
                "    dim_Date"
              ]
            }
          }
        ]
      },
      {
        "name": "vw CSI Finance",
        "columns": [
          {
            "name": "SalesID",
            "dataType": "int64",
            "sourceColumn": "SalesID"
          },
          {
            "name": "DS_PK",
            "dataType": "int64",
            "sourceColumn": "DS_PK"
          },
          {
            "name": "DS_SK",
            "dataType": "int64",
            "sourceColumn": "DS_SK"
          },
          {
            "name": "Contact person",
            "dataType": "string",
            "sourceColumn": "Contact person"
          },
          {
            "name": "Company",
            "dataType": "string",
            "sourceColumn": "Company"
          },
          {
            "name": "Company ID",
            "dataType": "string",
            "sourceColumn": "Company ID"
          },
          {
            "name": "Interaction Date",
            "dataType": "dateTime",
            "sourceColumn": "Interaction Date",
            "formatString": "dd/MM/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Interview Date",
            "dataType": "dateTime",
            "sourceColumn": "Interview Date",
            "formatString": "dd/MM/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Main Dealer",
            "dataType": "string",
            "sourceColumn": "Main Dealer"
          },
          {
            "name": "Dealer",
            "dataType": "string",
            "sourceColumn": "Dealer"
          },
          {
            "name": "Salesperson",
            "dataType": "string",
            "sourceColumn": "Salesperson"
          },
          {
            "name": "New Contact Y/N",
            "dataType": "string",
            "sourceColumn": "New Contact Y/N"
          },
          {
            "name": "New Contact",
            "dataType": "string",
            "sourceColumn": "New Contact"
          },
          {
            "name": "New Phone Y/N",
            "dataType": "string",
            "sourceColumn": "New Phone Y/N"
          },
          {
            "name": "New Phone",
            "dataType": "string",
            "sourceColumn": "New Phone"
          },
          {
            "name": "Contact Via Email Y/N",
            "dataType": "string",
            "sourceColumn": "Contact Via Email Y/N"
          },
          {
            "name": "New Email Y/N",
            "dataType": "string",
            "sourceColumn": "New Email Y/N"
          },
          {
            "name": "New Email",
            "dataType": "string",
            "sourceColumn": "New Email"
          },
          {
            "name": "Remove Contact Y/N",
            "dataType": "string",
            "sourceColumn": "Remove Contact Y/N"
          },
          {
            "name": "Name Withheld Yes/No",
            "dataType": "string",
            "sourceColumn": "Name Withheld Yes/No"
          },
          {
            "name": "Phone Answered Yes/No",
            "dataType": "string",
            "sourceColumn": "Phone Answered Yes/No"
          },
          {
            "name": "Survey Completed Yes/No",
            "dataType": "string",
            "sourceColumn": "Survey Completed Yes/No"
          },
          {
            "name": "Further Comments",
            "dataType": "string",
            "sourceColumn": "Further Comments"
          },
          {
            "name": "Question ID",
            "dataType": "string",
            "sourceColumn": "Question ID"
          },
          {
            "name": "Question",
            "dataType": "string",
            "sourceColumn": "Question",
            "sortByColumn": "Question ID"
          },
          {
            "name": "Question G",
            "dataType": "string",
            "sourceColumn": "Question G",
            "sortByColumn": "Question ID"
          },
          {
            "name": "Comments",
            "dataType": "string",
            "sourceColumn": "Comments"
          },
          {
            "name": "Points",
            "dataType": "string",
            "sourceColumn": "Points"
          },
          {
            "name": "Index",
            "dataType": "int64",
            "sourceColumn": "Index"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "MonthNo",
            "dataType": "int64",
            "sourceColumn": "MonthNo"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Points TXT",
            "dataType": "string",
            "sourceColumn": "Points TXT"
          },
          {
            "name": "Points TxT filter",
            "dataType": "string",
            "sourceColumn": "Points TxT filter"
          },
          {
            "name": "Index Filter",
            "dataType": "string",
            "sourceColumn": "Index Filter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Quarter Sort",
            "dataType": "string",
            "sourceColumn": "Quarter Sort"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Region ID",
            "dataType": "int64",
            "sourceColumn": "Region ID"
          },
          {
            "name": "Contact Changed",
            "dataType": "string",
            "sourceColumn": "Contact Changed"
          },
          {
            "type": "calculated",
            "name": "Finance MTD",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI Finance'[Interaction Date])",
              "RETURN",
              "IF(MONTH('vw CSI Finance'[Interaction Date])=MONTH(MAXDATE)&&YEAR('vw CSI Finance'[Interaction Date])=YEAR(MAXDATE),TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Finance PM",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI Finance'[Interaction Date])",
              "RETURN",
              "IF(MONTH('vw CSI Finance'[Interaction Date])=MONTH(MAXDATE)-1&&YEAR('vw CSI Finance'[Interaction Date])=YEAR(MAXDATE),TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Finance YTD",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI Finance'[Interaction Date])",
              "RETURN",
              "IF(YEAR('vw CSI Finance'[Interaction Date])=YEAR(MAXDATE),TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Finance LY",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI Finance'[Interaction Date])",
              "RETURN",
              "IF(YEAR('vw CSI Finance'[Interaction Date])=YEAR(MAXDATE)-1,TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Finance Rolling 12 Month",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI Finance'[Interaction Date])",
              "RETURN",
              "IF('vw CSI Finance'[Interaction Date]>=DATE(YEAR(MAXDATE)-1,MONTH(MAXDATE),DAY(MAXDATE))&&'vw CSI Finance'[Interaction Date]<=MAXDATE,TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    #\"dbo_vw CSI Finance\" = Source{[Schema=\"dbo\",Item=\"vw CSI Finance\"]}[Data]",
                "in",
                "    #\"dbo_vw CSI Finance\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Selected Finance Period",
            "expression": "SELECTEDVALUE('CSI Time Intelligence'[Finance Period])"
          },
          {
            "name": "Selected Main Dealer Finance",
            "expression": "IF(ISFILTERED('vw CSI Finance'[Main dealer]),SELECTEDVALUE('vw CSI Finance'[Main dealer]),\"All Dealers\")"
          },
          {
            "name": "Selected Dealer Finance",
            "expression": "IF(ISFILTERED('vw CSI Finance'[Dealer]),SELECTEDVALUE('vw CSI Finance'[Dealer]),\"All Dealers\")"
          },
          {
            "name": "Reporting Period Finance",
            "expression": "IF(ISFILTERED('CSI Time Intelligence'[Finance Period]),SELECTEDVALUE('CSI Time Intelligence'[Finance Period]),\"All Periods\")"
          },
          {
            "name": "Finance",
            "expression": "\"Finance\""
          },
          {
            "name": "Used Scania Finance N",
            "expression": "CALCULATE([Finance Tot Questions],'vw CSI Finance'[Question]=\"Used Scania finance (Yes/No)\",'vw CSI Finance'[Points TXT]=\"No\")",
            "formatString": "#,0"
          },
          {
            "name": "Used Scania Finance N Index",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period] = \"Year To Date\",",
              "    CALCULATE ( [Used Scania Finance N], 'vw CSI Finance'[Finance YTD] = TRUE () ),",
              "    IF (",
              "        [Selected Finance Period] = \"Previous Month\",",
              "        CALCULATE ( [Used Scania Finance N], 'vw CSI Finance'[Finance PM] = TRUE () ),",
              "        IF (",
              "            [Selected Finance Period] = \"Month To Date\",",
              "            CALCULATE ( [Used Scania Finance N], 'vw CSI Finance'[Finance MTD] = TRUE () ),",
              "            IF (",
              "                [Selected Finance Period] = \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Used Scania Finance N],",
              "                    'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                    [Selected Finance Period] = \"Last Year\",",
              "                    CALCULATE ( [Used Scania Finance N], 'vw CSI Finance'[Finance LY] = TRUE () ),",
              "                    [Used Scania Finance N]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Finance Tot Questions",
            "expression": "0+CALCULATE(DISTINCTCOUNT('vw CSI Finance'[SalesID]))",
            "formatString": "#,0"
          },
          {
            "name": "Finance Sample Size",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period] = \"Year To Date\",",
              "    CALCULATE ( [Finance Tot Questions], 'vw CSI Finance'[Finance YTD] = TRUE () ),",
              "    IF (",
              "        [Selected Finance Period] = \"Previous Month\",",
              "        CALCULATE ( [Finance Tot Questions], 'vw CSI Finance'[Finance PM] = TRUE () ),",
              "        IF (",
              "            [Selected Finance Period] = \"Month To Date\",",
              "            CALCULATE ( [Finance Tot Questions], 'vw CSI Finance'[Finance MTD] = TRUE () ),",
              "            IF (",
              "                [Selected Finance Period] = \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Finance Tot Questions],",
              "                    'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                    [Selected Finance Period] = \"Last Year\",",
              "                    CALCULATE ( [Finance Tot Questions], 'vw CSI Finance'[Finance LY] = TRUE () ),",
              "                    [Finance Tot Questions]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Completed Finance Survey",
            "expression": "0+CALCULATE('vw CSI Finance'[Finance Sample Size],'vw CSI Finance'[Survey Completed Yes/No]=\"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Why Not Scania Finance",
            "expression": "CALCULATE([Finance Sample Size (Table)],'vw CSI Finance'[Question]=\"Reason For Not Taking Scania Finance\",'vw CSI Finance'[Points]<>\"9\")",
            "formatString": "#,0"
          },
          {
            "name": "Finance Index",
            "expression": "0+CALCULATE(AVERAGE('vw CSI Finance'[Index]),'vw CSI Finance'[Index Filter]=\"TRUE\")",
            "formatString": "0.0"
          },
          {
            "name": "CSI Finance Index",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [Finance Index],",
              "        'vw CSI Finance'[Finance YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected Finance Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [Finance Index],",
              "           'vw CSI Finance'[Finance PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Finance Period]= \"Month To Date\",",
              "            CALCULATE (",
              "               [Finance Index],",
              "               'vw CSI Finance'[Finance MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected Finance Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Finance Index],",
              "                  'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected Finance Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [Finance Index],",
              "                      'vw CSI Finance'[Finance LY] = TRUE ()",
              "                    ),",
              "                     [Finance Index]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "CSI Finance Index (Card)",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [Finance Index],",
              "        'vw CSI Finance'[Finance YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected Finance Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [Finance Index],",
              "           'vw CSI Finance'[Finance PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Finance Period]= \"Month To Date\",",
              "            CALCULATE (",
              "               [Finance Index],",
              "               'vw CSI Finance'[Finance MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected Finance Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Finance Index],",
              "                  'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected Finance Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [Finance Index],",
              "                      'vw CSI Finance'[Finance LY] = TRUE ()",
              "                    ),",
              "                     [Finance Index]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Used Scania Finance",
            "expression": "CALCULATE([Finance Tot Questions],'vw CSI Finance'[Question]=\"Used Scania finance (Yes/No)\",'vw CSI Finance'[Points TXT]=\"No\"||'vw CSI Finance'[Points TXT]=\"Yes\")",
            "formatString": "#,0"
          },
          {
            "name": "Used Scania Finance Index",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [Used Scania Finance],",
              "        'vw CSI Finance'[Finance YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected Finance Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [Used Scania Finance],",
              "           'vw CSI Finance'[Finance PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Finance Period]= \"Month To Date\",",
              "            CALCULATE (",
              "              [Used Scania Finance],",
              "               'vw CSI Finance'[Finance MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected Finance Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                   [Used Scania Finance],",
              "                  'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected Finance Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                     [Used Scania Finance],",
              "                      'vw CSI Finance'[Finance LY] = TRUE ()",
              "                    ),",
              "                      [Used Scania Finance]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "CSI Used Scania Finance",
            "expression": "CALCULATE([Finance Sample Size (Table)],'vw CSI Finance'[Question]=\"Used Scania finance (Yes/No)\",'vw CSI Finance'[Points]<>\"9\")",
            "formatString": "#,0"
          },
          {
            "name": "Finance Tot Questions (Table)",
            "expression": "CALCULATE(DISTINCTCOUNT('vw CSI Finance'[SalesID]))",
            "formatString": "#,0"
          },
          {
            "name": "Finance Sample Size (Table)",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [Finance Tot Questions (Table)],",
              "        'vw CSI Finance'[Finance YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected Finance Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [Finance Tot Questions (Table)],",
              "           'vw CSI Finance'[Finance PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Finance Period]= \"Month To Date\",",
              "            CALCULATE (",
              "               [Finance Tot Questions (Table)],",
              "               'vw CSI Finance'[Finance MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected Finance Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Finance Tot Questions (Table)],",
              "                  'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected Finance Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [Finance Tot Questions (Table)],",
              "                      'vw CSI Finance'[Finance LY] = TRUE ()",
              "                    ),",
              "                     [Finance Tot Questions (Table)]\t",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Finance Index (Table)",
            "expression": "0+CALCULATE(AVERAGE('vw CSI Finance'[Index]),'vw CSI Finance'[Index Filter]=\"TRUE\")",
            "formatString": "0.0"
          },
          {
            "name": "CSI Finance Index (Table)",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [Finance Index (Table)],",
              "        'vw CSI Finance'[Finance YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected Finance Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [Finance Index (Table)],",
              "           'vw CSI Finance'[Finance PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Finance Period]= \"Month To Date\",",
              "            CALCULATE (",
              "               [Finance Index (Table)],",
              "               'vw CSI Finance'[Finance MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected Finance Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Finance Index (Table)],",
              "                  'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected Finance Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [Finance Index (Table)],",
              "                      'vw CSI Finance'[Finance LY] = TRUE ()",
              "                    ),",
              "                     [Finance Index (Table)]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Finance Tot Questions (Graph)",
            "expression": "CALCULATE(COUNT('vw CSI Finance'[SalesID]),'vw CSI Finance'[Points TxT filter]=\"TRUE\")",
            "formatString": "#,0"
          },
          {
            "name": "Finance Sample Size (Graph)",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [Finance Tot Questions (Graph)],",
              "        'vw CSI Finance'[Finance YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected Finance Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [Finance Tot Questions (Graph)],",
              "           'vw CSI Finance'[Finance PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Finance Period]= \"Month To Date\",",
              "            CALCULATE (",
              "               [Finance Tot Questions (Graph)],",
              "               'vw CSI Finance'[Finance MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected Finance Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Finance Tot Questions (Graph)],",
              "                  'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected Finance Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [Finance Tot Questions (Graph)],",
              "                      'vw CSI Finance'[Finance LY] = TRUE ()",
              "                    ),",
              "                     [Finance Tot Questions (Graph)]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "CSI Finance Sample Size (Graph)",
            "expression": [
              "",
              "IF (",
              "    [Selected Finance Period]= \"Year To Date\",",
              "    CALCULATE (",
              "        [Finance Sample Size (Graph)],",
              "        'vw CSI Finance'[Finance YTD] = TRUE ()",
              "    ),",
              "    IF (",
              "        [Selected Finance Period]= \"Previous Month\",",
              "        CALCULATE (",
              "           [Finance Sample Size (Graph)],",
              "           'vw CSI Finance'[Finance PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Finance Period]= \"Month To Date\",",
              "            CALCULATE (",
              "               [Finance Sample Size (Graph)],",
              "               'vw CSI Finance'[Finance MTD] = TRUE ()",
              "            ),",
              "            IF (",
              "                [Selected Finance Period]= \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Finance Sample Size (Graph)],",
              "                  'vw CSI Finance'[Finance Rolling 12 Month] = TRUE ()",
              "                ),",
              "                IF (",
              "                   [Selected Finance Period]= \"Last Year\",",
              "                    CALCULATE (",
              "                      [Finance Sample Size (Graph)],",
              "                      'vw CSI Finance'[Finance LY] = TRUE ()",
              "                    ),",
              "                     [Finance Sample Size (Graph)]",
              "                )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "vw CSI Service",
        "columns": [
          {
            "name": "ServiceID",
            "dataType": "int64",
            "sourceColumn": "ServiceID"
          },
          {
            "name": "DS_PK",
            "dataType": "int64",
            "sourceColumn": "DS_PK"
          },
          {
            "name": "DS_SK",
            "dataType": "int64",
            "sourceColumn": "DS_SK"
          },
          {
            "name": "Contact person",
            "dataType": "string",
            "sourceColumn": "Contact person"
          },
          {
            "name": "Company",
            "dataType": "string",
            "sourceColumn": "Company"
          },
          {
            "name": "Company ID",
            "dataType": "string",
            "sourceColumn": "Company ID"
          },
          {
            "name": "Interaction Date",
            "dataType": "dateTime",
            "sourceColumn": "Interaction Date",
            "formatString": "dd/MM/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Interview Date",
            "dataType": "dateTime",
            "sourceColumn": "Interview Date",
            "formatString": "dd/MM/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Main dealer",
            "dataType": "string",
            "sourceColumn": "Main dealer"
          },
          {
            "name": "Dealer",
            "dataType": "string",
            "sourceColumn": "Dealer"
          },
          {
            "name": "Salesperson",
            "dataType": "string",
            "sourceColumn": "Salesperson"
          },
          {
            "name": "New Contact",
            "dataType": "string",
            "sourceColumn": "New Contact"
          },
          {
            "name": "New Contact Y/N",
            "dataType": "string",
            "sourceColumn": "New Contact Y/N"
          },
          {
            "name": "New Phone",
            "dataType": "string",
            "sourceColumn": "New Phone"
          },
          {
            "name": "New Phone Y/N",
            "dataType": "string",
            "sourceColumn": "New Phone Y/N"
          },
          {
            "name": "New email Y/N",
            "dataType": "string",
            "sourceColumn": "New email Y/N"
          },
          {
            "name": "New Email",
            "dataType": "string",
            "sourceColumn": "New Email"
          },
          {
            "name": "Contact Via Email Y/N",
            "dataType": "string",
            "sourceColumn": "Contact Via Email Y/N"
          },
          {
            "name": "Remove Contact Y/N",
            "dataType": "string",
            "sourceColumn": "Remove Contact Y/N"
          },
          {
            "name": "Name Withheld Yes/No",
            "dataType": "string",
            "sourceColumn": "Name Withheld Yes/No"
          },
          {
            "name": "Phone Answered Yes/No",
            "dataType": "string",
            "sourceColumn": "Phone Answered Yes/No"
          },
          {
            "name": "Survey Completed Yes/No",
            "dataType": "string",
            "sourceColumn": "Survey Completed Yes/No"
          },
          {
            "name": "Further Comments",
            "dataType": "string",
            "sourceColumn": "Further Comments"
          },
          {
            "name": "Question ID",
            "dataType": "int64",
            "sourceColumn": "Question ID"
          },
          {
            "name": "Question",
            "dataType": "string",
            "sourceColumn": "Question",
            "sortByColumn": "Question ID"
          },
          {
            "name": "Comments",
            "dataType": "string",
            "sourceColumn": "Comments"
          },
          {
            "name": "Points",
            "dataType": "string",
            "sourceColumn": "Points"
          },
          {
            "name": "Index",
            "dataType": "int64",
            "sourceColumn": "Index"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "MonthNo",
            "dataType": "int64",
            "sourceColumn": "MonthNo"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Year",
            "dataType": "string",
            "sourceColumn": "Month Year",
            "sortByColumn": "Interval"
          },
          {
            "name": "Points TXT",
            "dataType": "string",
            "sourceColumn": "Points TXT"
          },
          {
            "name": "Points TxT filter",
            "dataType": "string",
            "sourceColumn": "Points TxT filter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Quarter Sort",
            "dataType": "int64",
            "sourceColumn": "Quarter Sort"
          },
          {
            "name": "Region ID",
            "dataType": "string",
            "sourceColumn": "Region ID"
          },
          {
            "name": "Depot ID",
            "dataType": "int64",
            "sourceColumn": "Depot ID"
          },
          {
            "name": "Contact Changed",
            "dataType": "string",
            "sourceColumn": "Contact Changed"
          },
          {
            "type": "calculated",
            "name": "Service MTD",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE =",
              "    MAX ( 'vw CSI Service'[Interaction Date] )",
              "RETURN",
              "    IF (",
              "        MONTH ( 'vw CSI Service'[Interaction Date] ) = MONTH ( MAXDATE )",
              "            && YEAR ( 'vw CSI Service'[Interaction Date] ) = YEAR ( MAXDATE ),",
              "        TRUE (),",
              "        FALSE ()",
              "    )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Service PM",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE =",
              "    MAX ( 'vw CSI Service'[Interaction Date] )",
              "RETURN",
              "    IF (",
              "        MONTH ( 'vw CSI Service'[Interaction Date] )",
              "            = MONTH ( MAXDATE ) - 1",
              "            && YEAR ( 'vw CSI Service'[Interaction Date] ) = YEAR ( MAXDATE ),",
              "        TRUE (),",
              "        FALSE ()",
              "    )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Service YTD",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI Service'[Interaction Date])",
              "RETURN",
              "IF(YEAR('vw CSI Service'[Interaction Date])=YEAR(MAXDATE),TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Service LY",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE =  MAX('vw CSI Service'[Interaction Date])",
              "RETURN",
              "IF(YEAR('vw CSI Service'[Interaction Date])=YEAR(MAXDATE)-1,TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Rollin 12 Months",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MAXDATE = MAX('vw CSI Service'[Interaction Date])",
              "RETURN",
              "IF('vw CSI Service'[Interaction Date]>=DATE(YEAR(MAXDATE)-1,MONTH(MAXDATE)-1,DAY(MAXDATE))&&'vw CSI Service'[Interaction Date]<=MAXDATE,TRUE(),FALSE())"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Question Filter",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "IF(OR('vw CSI Service'[Question]=\"Overall pQuestionerformance\",'vw CSI Service'[Question]=\"Recommendation\"),FALSE(),TRUE())",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculated",
            "name": "Interval",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MaxDate =",
              "    MAX ( 'vw CSI Service'[Interaction Date] )",
              "RETURN",
              "    IF (",
              "        DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 0,",
              "        11,",
              "        IF (",
              "            DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 1,",
              "            10,",
              "            IF (",
              "                DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 2,",
              "                9,",
              "                IF (",
              "                    DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 3,",
              "                    8,",
              "                    IF (",
              "                        DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 4,",
              "                        7,",
              "                        IF (",
              "                            DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 5,",
              "                            6,",
              "                            IF (",
              "                                DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 6,",
              "                                5,",
              "                                IF (",
              "                                    DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 7,",
              "                                    4,",
              "                                    IF (",
              "                                        DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 8,",
              "                                        3,",
              "                                        IF (",
              "                                            DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 9,",
              "                                            2,",
              "                                            IF (",
              "                                                DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 10,",
              "                                                1,",
              "                                                IF (",
              "                                                    DATEDIFF ( 'vw CSI Service'[Interaction Date], MaxDate, MONTH ) = 11,",
              "                                                    0,",
              "                                                    100",
              "                                                )",
              "                                            )",
              "                                        )",
              "                                    )",
              "                                )",
              "                            )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )"
            ]
          },
          {
            "type": "calculated",
            "name": "Question Copy",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "'vw CSI Service'[Question]",
            "sortByColumn": "Question ID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    #\"dbo_vw CSI Service\" = Source{[Schema=\"dbo\",Item=\"vw CSI Service\"]}[Data]",
                "in",
                "    #\"dbo_vw CSI Service\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Txt SalesPerson",
            "expression": "\"Salesperson\""
          },
          {
            "name": "Service",
            "expression": "\"Service\""
          },
          {
            "name": "Txt Interaction Date",
            "expression": "\"Interaction Date\""
          },
          {
            "name": "Txt Interview Date",
            "expression": "\"Interview Date\""
          },
          {
            "name": "Txt Main Dealer",
            "expression": "\"Main Dealer\""
          },
          {
            "name": "Txt Dealer",
            "expression": "\"Dealer\""
          },
          {
            "name": "Txt Contact Person",
            "expression": "\"Contact Person\""
          },
          {
            "name": "Txt Additional Information",
            "expression": "\"Additional Information\""
          },
          {
            "name": "Txt New Contact",
            "expression": "\"New Contact\""
          },
          {
            "name": "Txt New Phone",
            "expression": "\"New Phone\""
          },
          {
            "name": "Txt New Contact ?",
            "expression": "\"New Contact ?\""
          },
          {
            "name": "Txt Further Comments",
            "expression": "\"Further Comments\""
          },
          {
            "name": "Txt New Email",
            "expression": "\"New Email\""
          },
          {
            "name": "Selected Service Period",
            "expression": "SELECTEDVALUE('CSI Time Intelligence'[Service Period])"
          },
          {
            "name": "Completed Service Survey",
            "expression": "0+CALCULATE('vw CSI Service'[Service Sample Size],'vw CSI Service'[Survey Completed Yes/No]=\"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Phone Answered Y/N Service",
            "expression": "0+CALCULATE('vw CSI Service'[Service Sample Size],'vw CSI Service'[Phone Answered Yes/No]=\"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Service Tot Questions",
            "expression": "0+CALCULATE(DISTINCTCOUNT('vw CSI Service'[ServiceID]))"
          },
          {
            "name": "Service Sample Size",
            "expression": [
              "",
              "IF (  [Selected Service Period] = \"Year To Date\",",
              "    CALCULATE ( 'vw CSI Service'[Service Tot Questions], 'vw CSI Service'[Service YTD] = TRUE () ),",
              "    IF (",
              "        [Selected Service Period] = \"Previous Month\",",
              "        CALCULATE (",
              "            [Service Tot Questions],",
              "            'vw CSI Service'[Service PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Service Period] = \"Month To Date\",",
              "            CALCULATE ( 'vw CSI Service'[Service Tot Questions], 'vw CSI Service'[Service MTD]=TRUE () ),",
              "            IF (",
              "                [Selected Service Period] = \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Service Tot Questions],",
              "                    'vw CSI Service'[Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                     [Selected Service Period] = \"Last Year\",",
              "                    CALCULATE (",
              "                        [Service Tot Questions],",
              "                        'vw CSI Service'[Service LY] = TRUE ()",
              "                    ),",
              "                    [Service Tot Questions]",
              "            )",
              "        )",
              "    )",
              ")",
              "",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "CSI Target",
            "expression": "8.2"
          },
          {
            "name": "Completed Service Survey (Graph)",
            "expression": "0+CALCULATE('vw CSI Service'[Service Sample Size],'vw CSI Service'[Survey Completed Yes/No]=\"Y\",'vw CSI Service'[Points TxT filter]=\"TRUE\")",
            "formatString": "#,0"
          },
          {
            "name": "Completed Service Survey  (Graph) 1",
            "expression": "0+CALCULATE('vw CSI Service'[Service Sample Size],'vw CSI Service'[Survey Completed Yes/No]=\"Y\",'vw CSI Service'[Points TxT filter]=\"TRUE\")",
            "formatString": "#,0"
          },
          {
            "name": "CSI Index Format",
            "expression": [
              "SWITCH(TRUE(),'vw CSI Service'[CSI Service Index (Card 2)]>='vw CSI Service'[CSI Target],1",
              ",0)"
            ]
          },
          {
            "name": "Fixed First Visit %",
            "expression": "0+DIVIDE(CALCULATE('vw CSI Service'[Service Sample Size],'vw CSI Service'[Question]=\"Fixed first visit (Yes/No)\",'vw CSI Service'[Points]=\"Yes\"),'vw CSI Service'[Service Sample Size])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Selected Main Dealer Service",
            "expression": "IF(ISFILTERED('vw CSI Service'[Main dealer]),SELECTEDVALUE('vw CSI Service'[Main dealer]),\"All Dealers\")"
          },
          {
            "name": "Selected Dealer Service",
            "expression": "IF(ISFILTERED('vw CSI Service'[Dealer]),SELECTEDVALUE('vw CSI Service'[Dealer]),\"All Dealers\")"
          },
          {
            "name": "Reporting Period Service",
            "expression": "IF(ISFILTERED('CSI Time Intelligence'[Service Period]),SELECTEDVALUE('CSI Time Intelligence'[Service Period]),\"All Periods\")"
          },
          {
            "name": "Depot View Reporting Period",
            "expression": "IF(ISFILTERED('vw CSI Service'[Month Year]),SELECTEDVALUE('vw CSI Service'[Month Year]),\"Rolling 12 Months\")"
          },
          {
            "name": "Service Index",
            "expression": "CALCULATE(AVERAGE('vw CSI Service'[Index]),'vw CSI Service'[Points TxT filter]=\"TRUE\")",
            "formatString": "0.0"
          },
          {
            "name": "CSI Service Index",
            "expression": [
              "",
              "IF (",
              "    [Selected Service Period] = \"Year To Date\",",
              "    CALCULATE ( 'vw CSI Service'[Service Index], 'vw CSI Service'[Service YTD] = TRUE () ),",
              "    IF (",
              "        [Selected Service Period] = \"Previous Month\",",
              "        CALCULATE (",
              "            [Service Index],",
              "            'vw CSI Service'[Service PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Service Period] = \"Month To Date\",",
              "            CALCULATE ( 'vw CSI Service'[Service Index], 'vw CSI Service'[Service MTD]=TRUE () ),",
              "            IF (",
              "                [Selected Service Period] = \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Service Index],",
              "                    'vw CSI Service'[Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                     [Selected Service Period] = \"Last Year\",",
              "                    CALCULATE (",
              "                        [Service Index],",
              "                        'vw CSI Service'[Service LY] = TRUE ()",
              "                    ),",
              "                    [Service Index]",
              "            )",
              "        )",
              "    )",
              ")",
              "",
              ")"
            ],
            "formatString": "0"
          },
          {
            "name": "CSI Service Index (Card)",
            "expression": [
              "",
              "IF (",
              "    [Selected Service Period] = \"Year To Date\",",
              "    CALCULATE ( 'vw CSI Service'[Service Index], 'vw CSI Service'[Service YTD] = TRUE () ),",
              "    IF (",
              "        [Selected Service Period] = \"Previous Month\",",
              "        CALCULATE (",
              "            [Service Index],",
              "            'vw CSI Service'[Service PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Service Period] = \"Month To Date\",",
              "            CALCULATE ( 'vw CSI Service'[Service Index], 'vw CSI Service'[Service MTD]=TRUE () ),",
              "            IF (",
              "                [Selected Service Period] = \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Service Index],",
              "                    'vw CSI Service'[Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                     [Selected Service Period] = \"Last Year\",",
              "                    CALCULATE (",
              "                        [Service Index],",
              "                        'vw CSI Service'[Service LY] = TRUE ()",
              "                    ),",
              "                    [Service Index]",
              "            )",
              "        )",
              "    )",
              ")",
              "",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Service Index Colour",
            "expression": "CALCULATE(AVERAGE('vw CSI Service'[Index]))",
            "formatString": "0"
          },
          {
            "name": "Copy of Service Index",
            "expression": "CALCULATE(AVERAGE('vw CSI Service'[Index]),'vw CSI Service'[Points TxT filter]=\"TRUE\",DATESINPERIOD('vw CSI Service'[Interaction Date],MAX('vw CSI Service'[Interaction Date]),12,MONTH))",
            "formatString": "0.0"
          },
          {
            "name": "Service Index 2",
            "expression": "0+CALCULATE(AVERAGE('vw CSI Service'[Index]),'vw CSI Service'[Points TxT filter]=\"TRUE\",'vw CSI Service'[Question Filter]=TRUE())",
            "formatString": "0.0"
          },
          {
            "name": "CSI Service Index (Card 2)",
            "expression": [
              "",
              "IF (",
              "    [Selected Service Period] = \"Year To Date\",",
              "    CALCULATE ( 'vw CSI Service'[Service Index 2], 'vw CSI Service'[Service YTD] = TRUE () ),",
              "    IF (",
              "        [Selected Service Period] = \"Previous Month\",",
              "        CALCULATE (",
              "            [Service Index 2],",
              "            'vw CSI Service'[Service PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Service Period] = \"Month To Date\",",
              "            CALCULATE ( 'vw CSI Service'[Service Index 2], 'vw CSI Service'[Service MTD]=TRUE () ),",
              "            IF (",
              "                [Selected Service Period] = \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Service Index 2],",
              "                    'vw CSI Service'[Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                     [Selected Service Period] = \"Last Year\",",
              "                    CALCULATE (",
              "                        [Service Index 2],",
              "                        'vw CSI Service'[Service LY] = TRUE ()",
              "                    ),",
              "                    [Service Index 2]",
              "            )",
              "        )",
              "    )",
              ")",
              "",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Service Index 2(table)",
            "expression": "CALCULATE(AVERAGE('vw CSI Service'[Index]),'vw CSI Service'[Points TxT filter]=\"TRUE\",'vw CSI Service'[Question Filter]=TRUE())",
            "formatString": "0.0"
          },
          {
            "name": "Service YTD Service",
            "expression": "CALCULATE('vw CSI Service'[Service Index 2(table)],'vw CSI Service'[Service YTD]=TRUE())",
            "formatString": "0.0"
          },
          {
            "name": "CSI Service Index 2(Table)",
            "expression": [
              "",
              "IF (",
              "    [Selected Service Period] = \"Year To Date\",",
              "    CALCULATE ( 'vw CSI Service'[Service Index 2(table)], 'vw CSI Service'[Service YTD] = TRUE () ),",
              "    IF (",
              "        [Selected Service Period] = \"Previous Month\",",
              "        CALCULATE (",
              "            [Service Index 2(table)],",
              "            'vw CSI Service'[Service PM] = TRUE ()",
              "        ),",
              "        IF (",
              "            [Selected Service Period] = \"Month To Date\",",
              "            CALCULATE ( 'vw CSI Service'[Service Index 2(table)], 'vw CSI Service'[Service MTD]=TRUE () ),",
              "            IF (",
              "                [Selected Service Period] = \"Rolling 12 Months\",",
              "                CALCULATE (",
              "                    [Service Index 2(table)],",
              "                    'vw CSI Service'[Rollin 12 Months] = TRUE ()",
              "                ),",
              "                IF (",
              "                     [Selected Service Period] = \"Last Year\",",
              "                    CALCULATE (",
              "                        [Service Index 2(table)],",
              "                        'vw CSI Service'[Service LY] = TRUE ()",
              "                    ),",
              "                    [Service Index 2(table)]",
              "            )",
              "        )",
              "    )",
              ")",
              "",
              ")"
            ],
            "formatString": "0.0"
          },
          {
            "name": "Last Updated",
            "expression": "\"Last Updated\"&\" \"&\":\""
          }
        ]
      },
      {
        "name": "CSI Service Refresh Date",
        "columns": [
          {
            "name": "ServiceRefreshDate",
            "dataType": "dateTime",
            "sourceColumn": "ServiceRefreshDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    #\"dbo_CSI Service Refresh Date\" = Source{[Schema=\"dbo\",Item=\"CSI Service Refresh Date\"]}[Data]",
                "in",
                "    #\"dbo_CSI Service Refresh Date\""
              ]
            }
          }
        ]
      },
      {
        "name": "CSI New Sales Refresh Date",
        "columns": [
          {
            "name": "SalesRefreshDate",
            "dataType": "dateTime",
            "sourceColumn": "SalesRefreshDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    #\"dbo_CSI New Sales Refresh Date\" = Source{[Schema=\"dbo\",Item=\"CSI New Sales Refresh Date\"]}[Data]",
                "in",
                "    #\"dbo_CSI New Sales Refresh Date\""
              ]
            }
          }
        ]
      },
      {
        "name": "CSI Time Intelligence",
        "columns": [
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period"
          },
          {
            "name": "Service Period",
            "dataType": "string",
            "sourceColumn": "Service Period"
          },
          {
            "name": "Finance Period",
            "dataType": "string",
            "sourceColumn": "Finance Period"
          },
          {
            "name": "MOT Period",
            "dataType": "string",
            "sourceColumn": "MOT Period"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    #\"dbo_CSI Time Intelligence\" = Source{[Schema=\"dbo\",Item=\"CSI Time Intelligence\"]}[Data]",
                "in",
                "    #\"dbo_CSI Time Intelligence\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim Region",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "BK_Region",
            "dataType": "string",
            "sourceColumn": "BK_Region"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region"
          },
          {
            "name": "Region Type",
            "dataType": "string",
            "sourceColumn": "Region Type"
          },
          {
            "name": "VSBCompany",
            "dataType": "string",
            "sourceColumn": "VSBCompany"
          },
          {
            "name": "RMRisk",
            "dataType": "string",
            "sourceColumn": "RMRisk"
          },
          {
            "name": "DW_DateCreated",
            "dataType": "dateTime",
            "sourceColumn": "DW_DateCreated"
          },
          {
            "name": "DW_DateModified",
            "dataType": "dateTime",
            "sourceColumn": "DW_DateModified"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    dim_Region = Source{[Schema=\"dim\",Item=\"Region\"]}[Data]",
                "in",
                "    dim_Region"
              ]
            }
          }
        ]
      },
      {
        "name": "dim Depot",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "PoSCompany",
            "dataType": "string",
            "sourceColumn": "PoSCompany"
          },
          {
            "name": "BK_Depot",
            "dataType": "int64",
            "sourceColumn": "BK_Depot"
          },
          {
            "name": "Depot",
            "dataType": "string",
            "sourceColumn": "Depot"
          },
          {
            "name": "Depot Number",
            "dataType": "string",
            "sourceColumn": "Depot Number"
          },
          {
            "name": "Cost Centre",
            "dataType": "string",
            "sourceColumn": "Cost Centre"
          },
          {
            "name": "Depot Type",
            "dataType": "string",
            "sourceColumn": "Depot Type"
          },
          {
            "name": "Depot Status",
            "dataType": "string",
            "sourceColumn": "Depot Status"
          },
          {
            "name": "Region",
            "dataType": "int64",
            "sourceColumn": "Region"
          },
          {
            "name": "Post Code",
            "dataType": "string",
            "sourceColumn": "Post Code"
          },
          {
            "name": "Hours Mapping Name",
            "dataType": "string",
            "sourceColumn": "Hours Mapping Name"
          },
          {
            "name": "MOT Preparer ID",
            "dataType": "string",
            "sourceColumn": "MOT Preparer ID"
          },
          {
            "name": "DW_DateCreated",
            "dataType": "dateTime",
            "sourceColumn": "DW_DateCreated"
          },
          {
            "name": "DW_DateModified",
            "dataType": "dateTime",
            "sourceColumn": "DW_DateModified"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/sgbsql01 database windows net;KPI_Dashboards\",",
                "    dim_Depot = Source{[Schema=\"dim\",Item=\"Depot\"]}[Data]",
                "in",
                "    dim_Depot"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "c78ef7d9-12c5-4a45-8873-38a843885dc0",
        "fromTable": "vw CSI New Sales",
        "fromColumn": "Interaction Date",
        "toTable": "dim Date",
        "toColumn": "Date"
      },
      {
        "name": "2611a067-2835-4081-a8eb-7f1d52d96e6a",
        "fromTable": "vw CSI Finance",
        "fromColumn": "Interaction Date",
        "toTable": "dim Date",
        "toColumn": "Date"
      },
      {
        "name": "c87d3ad6-360f-428e-bcd1-1752cb9bb8cd",
        "fromTable": "vw CSI Service",
        "fromColumn": "Interaction Date",
        "toTable": "dim Date",
        "toColumn": "Date"
      },
      {
        "name": "db85423e-3837-442f-b081-b24c84b9b0b6",
        "fromTable": "dim Depot",
        "fromColumn": "Region",
        "toTable": "dim Region",
        "toColumn": "ID"
      },
      {
        "name": "da1fb59d-86d3-4d89-947f-1ba05a2b7644",
        "fromTable": "vw CSI Finance",
        "fromColumn": "Region ID",
        "toTable": "dim Region",
        "toColumn": "ID"
      },
      {
        "name": "66a50c60-305f-408a-9cbc-65804d835e4f",
        "fromTable": "vw CSI New Sales",
        "fromColumn": "Region ID",
        "toTable": "dim Region",
        "toColumn": "ID"
      },
      {
        "name": "11fb1705-7b3e-47a7-a980-8e9f7c6bd868",
        "fromTable": "vw CSI Service",
        "fromColumn": "Depot ID",
        "toTable": "dim Depot",
        "toColumn": "ID"
      }
    ],
    "roles": [
      {
        "name": "Wholly Owned",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:83a34515-2f68-4dfb-afdd-e8c0ce0796f1@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:83a34515-2f68-4dfb-afdd-e8c0ce0796f1@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ]
      },
      {
        "name": "Scania Finance",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:e400aac2-b7ac-47b8-bc8c-32f904edc46e@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:e400aac2-b7ac-47b8-bc8c-32f904edc46e@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "vw CSI Finance",
            "filterExpression": "'vw CSI Finance'[Category]=\"Finance\""
          },
          {
            "name": "vw CSI New Sales",
            "columnPermissions": [
              {
                "name": "SalesID",
                "metadataPermission": "none"
              },
              {
                "name": "DS_PK",
                "metadataPermission": "none"
              },
              {
                "name": "DS_SK",
                "metadataPermission": "none"
              },
              {
                "name": "Contact person",
                "metadataPermission": "none"
              },
              {
                "name": "Company",
                "metadataPermission": "none"
              },
              {
                "name": "Company ID",
                "metadataPermission": "none"
              },
              {
                "name": "Interaction Date",
                "metadataPermission": "none"
              },
              {
                "name": "Interview Date",
                "metadataPermission": "none"
              },
              {
                "name": "Main Dealer",
                "metadataPermission": "none"
              },
              {
                "name": "Dealer",
                "metadataPermission": "none"
              },
              {
                "name": "Salesperson",
                "metadataPermission": "none"
              },
              {
                "name": "New Contact Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "New Contact",
                "metadataPermission": "none"
              },
              {
                "name": "New Phone Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "New Phone",
                "metadataPermission": "none"
              },
              {
                "name": "Contact Via Email Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "New Email Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "New Email",
                "metadataPermission": "none"
              },
              {
                "name": "Remove Contact Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "Name Withheld Yes/No",
                "metadataPermission": "none"
              },
              {
                "name": "Phone Answered Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "Survey Completed Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "Further Comments",
                "metadataPermission": "none"
              },
              {
                "name": "Question ID",
                "metadataPermission": "none"
              },
              {
                "name": "Question",
                "metadataPermission": "none"
              },
              {
                "name": "Comments",
                "metadataPermission": "none"
              },
              {
                "name": "Points",
                "metadataPermission": "none"
              },
              {
                "name": "Index",
                "metadataPermission": "none"
              },
              {
                "name": "Year",
                "metadataPermission": "none"
              },
              {
                "name": "MonthNo",
                "metadataPermission": "none"
              },
              {
                "name": "Month",
                "metadataPermission": "none"
              },
              {
                "name": "Points TXT",
                "metadataPermission": "none"
              },
              {
                "name": "Points TxT filter",
                "metadataPermission": "none"
              },
              {
                "name": "Quarter",
                "metadataPermission": "none"
              },
              {
                "name": "Quarter Sort",
                "metadataPermission": "none"
              },
              {
                "name": "Region ID",
                "metadataPermission": "none"
              },
              {
                "name": "Contact Changed",
                "metadataPermission": "none"
              },
              {
                "name": "NewSales MTD",
                "metadataPermission": "none"
              },
              {
                "name": "NewSales PM",
                "metadataPermission": "none"
              },
              {
                "name": "NewSales YTD",
                "metadataPermission": "none"
              },
              {
                "name": "NewSales LY",
                "metadataPermission": "none"
              },
              {
                "name": "NewSales Rollin 12 Months",
                "metadataPermission": "none"
              },
              {
                "name": "Question Filter",
                "metadataPermission": "none"
              },
              {
                "name": "Interval",
                "metadataPermission": "none"
              },
              {
                "name": "Month Year",
                "metadataPermission": "none"
              },
              {
                "name": "Rolling Month Sort",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "dim Date",
            "columnPermissions": [
              {
                "name": "ID",
                "metadataPermission": "none"
              },
              {
                "name": "Date",
                "metadataPermission": "none"
              },
              {
                "name": "Year",
                "metadataPermission": "none"
              },
              {
                "name": "Year Name",
                "metadataPermission": "none"
              },
              {
                "name": "Month",
                "metadataPermission": "none"
              },
              {
                "name": "Month Name",
                "metadataPermission": "none"
              },
              {
                "name": "Quarter",
                "metadataPermission": "none"
              },
              {
                "name": "Quarter Name",
                "metadataPermission": "none"
              },
              {
                "name": "Quarter Year Name",
                "metadataPermission": "none"
              },
              {
                "name": "Week Start Date",
                "metadataPermission": "none"
              },
              {
                "name": "Week Name",
                "metadataPermission": "none"
              },
              {
                "name": "Day Name",
                "metadataPermission": "none"
              },
              {
                "name": "Day",
                "metadataPermission": "none"
              },
              {
                "name": "Short Day Name",
                "metadataPermission": "none"
              },
              {
                "name": "Short Month Name",
                "metadataPermission": "none"
              },
              {
                "name": "Day Of Week",
                "metadataPermission": "none"
              },
              {
                "name": "Year Month",
                "metadataPermission": "none"
              },
              {
                "name": "Is Scottish Public Holiday",
                "metadataPermission": "none"
              },
              {
                "name": "Is English Public Holiday",
                "metadataPermission": "none"
              },
              {
                "name": "Is Current Revenue Period",
                "metadataPermission": "none"
              },
              {
                "name": "Is Previous Revenue Period",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "vw CSI Service",
            "columnPermissions": [
              {
                "name": "ServiceID",
                "metadataPermission": "none"
              },
              {
                "name": "DS_PK",
                "metadataPermission": "none"
              },
              {
                "name": "DS_SK",
                "metadataPermission": "none"
              },
              {
                "name": "Contact person",
                "metadataPermission": "none"
              },
              {
                "name": "Company",
                "metadataPermission": "none"
              },
              {
                "name": "Company ID",
                "metadataPermission": "none"
              },
              {
                "name": "Interaction Date",
                "metadataPermission": "none"
              },
              {
                "name": "Interview Date",
                "metadataPermission": "none"
              },
              {
                "name": "Main dealer",
                "metadataPermission": "none"
              },
              {
                "name": "Dealer",
                "metadataPermission": "none"
              },
              {
                "name": "Salesperson",
                "metadataPermission": "none"
              },
              {
                "name": "New Contact",
                "metadataPermission": "none"
              },
              {
                "name": "New Contact Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "New Phone",
                "metadataPermission": "none"
              },
              {
                "name": "New Phone Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "New email Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "New Email",
                "metadataPermission": "none"
              },
              {
                "name": "Contact Via Email Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "Remove Contact Y/N",
                "metadataPermission": "none"
              },
              {
                "name": "Name Withheld Yes/No",
                "metadataPermission": "none"
              },
              {
                "name": "Phone Answered Yes/No",
                "metadataPermission": "none"
              },
              {
                "name": "Survey Completed Yes/No",
                "metadataPermission": "none"
              },
              {
                "name": "Further Comments",
                "metadataPermission": "none"
              },
              {
                "name": "Question ID",
                "metadataPermission": "none"
              },
              {
                "name": "Question",
                "metadataPermission": "none"
              },
              {
                "name": "Comments",
                "metadataPermission": "none"
              },
              {
                "name": "Points",
                "metadataPermission": "none"
              },
              {
                "name": "Index",
                "metadataPermission": "none"
              },
              {
                "name": "Year",
                "metadataPermission": "none"
              },
              {
                "name": "MonthNo",
                "metadataPermission": "none"
              },
              {
                "name": "Month",
                "metadataPermission": "none"
              },
              {
                "name": "Month Year",
                "metadataPermission": "none"
              },
              {
                "name": "Points TXT",
                "metadataPermission": "none"
              },
              {
                "name": "Points TxT filter",
                "metadataPermission": "none"
              },
              {
                "name": "Quarter",
                "metadataPermission": "none"
              },
              {
                "name": "Quarter Sort",
                "metadataPermission": "none"
              },
              {
                "name": "Region ID",
                "metadataPermission": "none"
              },
              {
                "name": "Depot ID",
                "metadataPermission": "none"
              },
              {
                "name": "Contact Changed",
                "metadataPermission": "none"
              },
              {
                "name": "Service MTD",
                "metadataPermission": "none"
              },
              {
                "name": "Service PM",
                "metadataPermission": "none"
              },
              {
                "name": "Service YTD",
                "metadataPermission": "none"
              },
              {
                "name": "Service LY",
                "metadataPermission": "none"
              },
              {
                "name": "Rollin 12 Months",
                "metadataPermission": "none"
              },
              {
                "name": "Question Filter",
                "metadataPermission": "none"
              },
              {
                "name": "Interval",
                "metadataPermission": "none"
              },
              {
                "name": "Question Copy",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "CSI Service Refresh Date",
            "columnPermissions": [
              {
                "name": "ServiceRefreshDate",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "CSI New Sales Refresh Date",
            "columnPermissions": [
              {
                "name": "SalesRefreshDate",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "CSI Time Intelligence",
            "columnPermissions": [
              {
                "name": "Period",
                "metadataPermission": "none"
              },
              {
                "name": "Service Period",
                "metadataPermission": "none"
              },
              {
                "name": "Finance Period",
                "metadataPermission": "none"
              },
              {
                "name": "MOT Period",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "dim Region",
            "columnPermissions": [
              {
                "name": "ID",
                "metadataPermission": "none"
              },
              {
                "name": "BK_Region",
                "metadataPermission": "none"
              },
              {
                "name": "Region",
                "metadataPermission": "none"
              },
              {
                "name": "Region Type",
                "metadataPermission": "none"
              },
              {
                "name": "VSBCompany",
                "metadataPermission": "none"
              },
              {
                "name": "RMRisk",
                "metadataPermission": "none"
              },
              {
                "name": "DW_DateCreated",
                "metadataPermission": "none"
              },
              {
                "name": "DW_DateModified",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "dim Depot",
            "columnPermissions": [
              {
                "name": "ID",
                "metadataPermission": "none"
              },
              {
                "name": "PoSCompany",
                "metadataPermission": "none"
              },
              {
                "name": "BK_Depot",
                "metadataPermission": "none"
              },
              {
                "name": "Depot",
                "metadataPermission": "none"
              },
              {
                "name": "Depot Number",
                "metadataPermission": "none"
              },
              {
                "name": "Cost Centre",
                "metadataPermission": "none"
              },
              {
                "name": "Depot Type",
                "metadataPermission": "none"
              },
              {
                "name": "Depot Status",
                "metadataPermission": "none"
              },
              {
                "name": "Region",
                "metadataPermission": "none"
              },
              {
                "name": "Post Code",
                "metadataPermission": "none"
              },
              {
                "name": "Hours Mapping Name",
                "metadataPermission": "none"
              },
              {
                "name": "MOT Preparer ID",
                "metadataPermission": "none"
              },
              {
                "name": "DW_DateCreated",
                "metadataPermission": "none"
              },
              {
                "name": "DW_DateModified",
                "metadataPermission": "none"
              }
            ]
          }
        ]
      },
      {
        "name": "All East",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:69eaef4c-5dda-42ab-8394-9c1c0099edb8@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:69eaef4c-5dda-42ab-8394-9c1c0099edb8@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Region",
            "filterExpression": "'dim Region'[Region]=\"East\""
          }
        ]
      },
      {
        "name": "All North",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:a1b20262-360e-4059-bc7f-9ef4d2a49a34@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:a1b20262-360e-4059-bc7f-9ef4d2a49a34@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Region",
            "filterExpression": "'dim Region'[Region]=\"North\""
          }
        ]
      },
      {
        "name": "All Scotland",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:8dcd97bc-3cc5-4786-99c5-9f477c8f9b24@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:8dcd97bc-3cc5-4786-99c5-9f477c8f9b24@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Region",
            "filterExpression": "'dim Region'[Region]=\"Scotland\""
          }
        ]
      },
      {
        "name": "All South East",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:3d385598-86bc-45bb-b7ef-3c060f387219@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:3d385598-86bc-45bb-b7ef-3c060f387219@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Region",
            "filterExpression": "'dim Region'[Region]=\"South East\""
          }
        ]
      },
      {
        "name": "All South West",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:9ecc7a81-1a52-4f7e-ace6-63d268123db3@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:9ecc7a81-1a52-4f7e-ace6-63d268123db3@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Region",
            "filterExpression": "'dim Region'[Region]=\"South West\""
          }
        ]
      },
      {
        "name": "Abingdon",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:c3fa599e-f7df-4232-a69a-cb8df39e28b4@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:c3fa599e-f7df-4232-a69a-cb8df39e28b4@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Abingdon\""
          }
        ]
      },
      {
        "name": "Avonmouth",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:ae679df2-46a9-4c5f-b478-2df2ad1a2189@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:ae679df2-46a9-4c5f-b478-2df2ad1a2189@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Avonmouth\""
          }
        ]
      },
      {
        "name": "Banbury",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:5fdcee5d-e2b9-4db5-846f-5f3fd7be8383@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:5fdcee5d-e2b9-4db5-846f-5f3fd7be8383@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Banbury\""
          }
        ]
      },
      {
        "name": "Bridgwater",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:44ecede4-a5f0-4a35-b8a9-d4237824d7e0@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:44ecede4-a5f0-4a35-b8a9-d4237824d7e0@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Bridgwater\""
          }
        ]
      },
      {
        "name": "Exeter",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:79526c26-d581-463f-95e1-c19c58e66406@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:79526c26-d581-463f-95e1-c19c58e66406@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Exeter\""
          }
        ]
      },
      {
        "name": "Fareham",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:dfa306c8-1378-4edf-85e6-4e6b86c46a7e@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:dfa306c8-1378-4edf-85e6-4e6b86c46a7e@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Fareham\""
          }
        ]
      },
      {
        "name": "Poole",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:6b23558d-4de4-4b40-b3b9-741e07d7a96e@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:6b23558d-4de4-4b40-b3b9-741e07d7a96e@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Poole\""
          }
        ]
      },
      {
        "name": "Redruth",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:587e8b7e-00d2-4569-9728-093309035aa6@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:587e8b7e-00d2-4569-9728-093309035aa6@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Redruth\""
          }
        ]
      },
      {
        "name": "Shepton Mallet",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:be4a12d1-e02e-433a-a714-85719d0b5db5@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:be4a12d1-e02e-433a-a714-85719d0b5db5@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Shepton Mallet\""
          }
        ]
      },
      {
        "name": "Southampton",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:1a42f5df-260c-46c5-8dc9-fc768020d1d7@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:1a42f5df-260c-46c5-8dc9-fc768020d1d7@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Southampton\""
          }
        ]
      },
      {
        "name": "Swindon",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:1cfc0bd2-38c8-4021-b6f4-e38f9a628052@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:1cfc0bd2-38c8-4021-b6f4-e38f9a628052@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "dim Depot",
            "filterExpression": "'dim Depot'[Depot]=\"Swindon\""
          }
        ]
      },
      {
        "name": "Executive Team",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:3a3892e4-f2d9-4df8-9b95-d1a2c9dfac3f@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "memberId": "obj:3a3892e4-f2d9-4df8-9b95-d1a2c9dfac3f@3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac",
            "identityProvider": "AzureAD"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}